### ISSUE TITLE
cannot launch shell; systemd-machined is not active

### ISSUE THREAD

**Issue by ZephireNZ** [arkane-systems/bottle-imp#2]
First of all thanks for this! Have been using genie for ages.

I am using [ArchWSL](https://github.com/yuk7/ArchWSL) and have installed imp with the Makefile.

After running `imp -i` and shutting down WSL, I attempted to create a new session with `wsl imp -s` but it gives the error:

`imp: cannot launch shell; systemd-machined is not active`

I am able to start this service manually and then imp works, but it appears it can't be enabled as a service:

```
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
```

Because of that, when WSL is shutdown and starts back up, the same error happens.

Any ideas? I am wondering if there's some kind of difference in behaviour between Debian and Arch.

**Comment by cerebrate** [comment]
Well, this is weird.

Ordinarily, this isn't a problem on Debian. However, it turns out that I can _disable_ systemd-machined on Debian, at which point I get this error, and that you can't _enable_ systemd-machined on Debian either (same error as above, because there aren't any of those settings).

So, that's... interesting.

**Comment by cerebrate** [comment]
And despite reinstalling the systemd-container package, and then poking around manually through the source for the systemd packages, I can't find whatever is _supposed_ to be starting systemd-machined.

So, um.

Until we figure this one out, I can work around it temporarily with

```
sudo ln -s /lib/systemd/system/systemd-machined.service /etc/systemd/system/multi-user.target.wants/systemd-machined.service
```

which manually does what enabling it would do, if it could be enabled, and this will probably work for you as well. Permanent solution is pending.

**Comment by ZephireNZ** [comment]
Yep that indeed worked.

Certainly an odd situation, maybe Debian pre-links that whereas Arch does not.

**Comment by theAeon** [comment]
same issue, same solution on suse tumbleweed.

**Comment by cerebrate** [comment]
Patch added to 0.4. I'm going to close this but leave it pinned as a reminder to find out what's really going on here.
